import { notFound } from 'next/navigation';
import { requireUser } from '@pumni/auth';
import { getRoom, getQueue, WatchRoom } from '@/features/watch';

// PageProps is a global generated by `next typegen` (.next/types/routes.d.ts) —
// params type is derived from the real segment tree, so it can't drift.
export default async function WatchRoomPage({ params }: PageProps<'/watch/[roomId]'>) {
  const user = await requireUser();
  const { roomId } = await params;

  const [room, initialQueueItems] = await Promise.all([getRoom(roomId), getQueue(roomId)]);

  if (!room) {
    notFound();
  }

  return <WatchRoom room={room} userId={user.id} initialQueueItems={initialQueueItems} />;
}
