import "server-only";

import { serverEnvSchema } from "./server-schema";

export const serverEnv = serverEnvSchema.parse({
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY:
    process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,
  SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
  NEXT_PUBLIC_JELLYFIN_URL: process.env.NEXT_PUBLIC_JELLYFIN_URL,
  JELLYFIN_URL: process.env.JELLYFIN_URL,
  JELLYFIN_API_KEY: process.env.JELLYFIN_API_KEY,
  JELLYFIN_USER: process.env.JELLYFIN_USER,
  JELLYFIN_PASSWORD: process.env.JELLYFIN_PASSWORD,
});
